// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5Pm0hahu8aVPVkGDnb_5P1aTQLa9Dx4',
    appId: '1:674428314633:web:4ccc5c6465eae7e6c0c4d8',
    messagingSenderId: '674428314633',
    projectId: 'cs310-group-14',
    authDomain: 'cs310-group-14.firebaseapp.com',
    storageBucket: 'cs310-group-14.firebasestorage.app',
    measurementId: 'G-WMEBE6TNKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0o-S8ysbAN5l71WVUOEhOvbCIJVUuNU',
    appId: '1:674428314633:android:1bd64b6007b1184fc0c4d8',
    messagingSenderId: '674428314633',
    projectId: 'cs310-group-14',
    storageBucket: 'cs310-group-14.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5Pm0hahu8aVPVkGDnb_5P1aTQLa9Dx4',
    appId: '1:674428314633:web:5624bf76128bd1e0c0c4d8',
    messagingSenderId: '674428314633',
    projectId: 'cs310-group-14',
    authDomain: 'cs310-group-14.firebaseapp.com',
    storageBucket: 'cs310-group-14.firebasestorage.app',
    measurementId: 'G-HBKHLQHQW6',
  );
}
